language: java
jdk: openjdk8
env:
  - CODECOV_TOKEN=dc6645f0-7c7f-457b-ae19-ad48c0249168
cache:
  directories:
    - $HOME/.m2
script: mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)