apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: sobre
spec:
  selector:
    matchLabels:
      app: sobre
  replicas: 1
  template:
    metadata:
      labels:
        app: sobre
    spec:
      containers:
        - name: sobre-test # 容器名词
          image: sobre # 镜像
          imagePullPolicy: Always # 镜像拉取策略