logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    username: root
    password: zxj19991213
    url: jdbc:mysql://47.98.131.150:3306/todo
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1
  jpa:
    generate-ddl: false
    open-in-view: false
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl