apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "sobre-chart.labels" . | indent 4 }}
spec:
  selector:
  {{- include "sobre-chart.selectLabels" . | indent 4 }}
  type: {{ .Values.service.type }}
  {{- include "sobre-chart.ports" . | indent 2 }}

